name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install dependencies
        run: npm ci
      - name: Test with Jest
        run: npm run test:jest
      - name: Build with webpack
        run: npm run build
